image: node:lts-bullseye
# Set this if you intend to use Git submodules
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_ENV: production

default:
  before_script:
    # Not using node container (neither alpine nor bullseye-slim), since for
    # some unknown reason npm build fails with them. Works when `
    # bullseye-lts`image is used and npm reinstalled in pipeline)
    - apt update && apt upgrade && apt install -y npm
    - git submodule update --init --recursive
    - npm install shx
    - npm run clean:install
    - npm install

test:
  script:
    - npm test
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  script:
    - npm run build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
